version: 2
updates:
    - package-ecosystem: npm
      directory: "/"
      schedule:
          interval: weekly
          day: monday
          time: "00:05"
          timezone: Europe/Berlin
      open-pull-requests-limit: 5
      assignees:
          - Tbs
      versioning-strategy: increase
      labels:
          - "dependencies"
          - "npm"

    - package-ecosystem: github-actions
      directory: "/"
      schedule:
          interval: weekly
          day: monday
          time: "00:10"
          timezone: Europe/Berlin
      open-pull-requests-limit: 5
      assignees:
          - Tbs
      labels:
          - "dependencies"
          - "github-actions"
