/**
 * Definiert die Struktur für einen ioBroker-Datenpunkt.
 * Wird genutzt, um die Luxtronik-Werte dynamisch anzulegen.
 */
export interface StateDefinition {
	/** Name des Datenpunkts */
	name: string;
	/** ioBroker-Rolle des Datenpunkts */
	role: string;
	/** Datentyp des Datenpunkts */
	type: "number" | "string" | "boolean" | "json";
	/** Einheit des Wertes (optional) */
	unit?: string;
	/** Schreibzugriff erlaubt (optional) */
	write?: boolean;
	/** Verzeichnis */
	folder: string;
	/** Die ID, die luxtronik2 zum Schreiben/Lesen erwartet */
	luxWriteId?: string;
	/** Kennzeichnung für rein virtuelle/berechnete Datenpunkte */
	isVirtual?: boolean;
	/** Optionaler Standardwert für den Datenpunkt */
	def?: any;
	/** Optionaler Minimalwert */
	min?: number;
	/** Optionaler Maximalwert */
	max?: number;
	/** Optionaler Umrechnungsfaktor */
	factor?: number;
	/** Optionales Mapping für numerische Werte zu Texten */
	states?: Record<number, string>;
	/** NEU: Bestimmt explizit die exakte Datenquelle an der Luxtronik */
	dataSource?: "raw_value" | "raw_parameter" | "value" | "parameter" | "additional";
}

/**
 * Mapping-Katalog für die Luxtronik-Werte.
 */
export const STATE_MAPPING: Record<string, StateDefinition> = {
	// ==========================================
	// Informationen & Values (Lesbar)
	// ==========================================
	// Temperaturen
	temperature_supply: {
		folder: "Informationen.01_Temperaturen",
		name: "Vorlauftemperatur",
		role: "value.temperature",
		type: "number",
		unit: "°C",
		dataSource: "value",
	},
	temperature_return: {
		folder: "Informationen.01_Temperaturen",
		name: "Rücklauftemperatur",
		role: "value.temperature",
		type: "number",
		unit: "°C",
		dataSource: "value",
	},
	// Virtuelle Berechnungen
	spreizung_vorlauf_ruecklauf: {
		folder: "Informationen.01_Temperaturen", // Passe den Ordner an den Ort an, wo deine Temperaturen liegen
		name: "Spreizung Vorlauf - Rücklauf",
		role: "value.temperature",
		type: "number",
		unit: "K",
		isVirtual: true,
	},
	temperature_target_return: {
		folder: "Informationen.01_Temperaturen",
		name: "Rückl.-Soll-Temperatur",
		role: "value.temperature",
		type: "number",
		unit: "°C",
		dataSource: "value",
	},
	temperature_hot_gas: {
		folder: "Informationen.01_Temperaturen",
		name: "Heissgas-Temperatur",
		role: "value.temperature",
		type: "number",
		unit: "°C",
		dataSource: "value",
	},
	temperature_outside: {
		folder: "Informationen.01_Temperaturen",
		name: "Außentemperatur",
		role: "value.temperature",
		type: "number",
		unit: "°C",
		dataSource: "value",
	},
	Mitteltemperatur: {
		folder: "Informationen.01_Temperaturen",
		name: "Value 16 (ID_WEB_Mitteltemperatur)",
		role: "value",
		type: "number",
		write: false,
		luxWriteId: "16",
		unit: "°C",
		factor: 10,
		dataSource: "raw_value",
	},
	temperature_hot_water: {
		folder: "Informationen.01_Temperaturen",
		name: "Warmwassertemperatur",
		role: "value.temperature",
		type: "number",
		unit: "°C",
		dataSource: "value",
	},
	Wamwassertemperatur_Ist: {
		folder: "Informationen.01_Temperaturen",
		name: "Value 17 (ID_WEB_Temperatur_TBW)",
		role: "value.temperature",
		type: "number",
		unit: "°C",
		write: false,
		luxWriteId: "17",
		factor: 10,
		dataSource: "raw_value",
	},
	Wamwassertemperatur_Soll: {
		folder: "Informationen.01_Temperaturen",
		name: "Value 18 (ID_WEB_Einst_BWS_akt)",
		role: "value.temperature",
		type: "number",
		unit: "°C",
		write: false,
		luxWriteId: "18",
		factor: 10,
		dataSource: "raw_value",
	},
	temperature_heat_source_in: {
		folder: "Informationen.01_Temperaturen",
		name: "Wärmequelle Eintritt",
		role: "value.temperature",
		type: "number",
		unit: "°C",
		dataSource: "value",
	},
	temperature_overheating_target: {
		folder: "Informationen.01_Temperaturen",
		name: "Überhitzung Soll",
		role: "value.temperature",
		type: "number",
		unit: "K",
		dataSource: "value",
	},
	temperature_compressor1_heating: {
		folder: "Informationen.01_Temperaturen",
		name: "Heißgas Kompressor 1",
		role: "value.temperature",
		type: "number",
		unit: "°C",
		dataSource: "value",
	},
	temperature_overheating: {
		folder: "Informationen.01_Temperaturen",
		name: "Überhitzung Ist",
		role: "value.temperature",
		type: "number",
		unit: "°C",
		dataSource: "value",
	},
	temperature_intake_compressor1: {
		folder: "Informationen.01_Temperaturen",
		name: "Saugstatus Kompressor 1 Temperatur",
		role: "value.temperature",
		type: "number",
		unit: "°C",
		dataSource: "value",
	},
	temperature_intake_evaporation: {
		folder: "Informationen.01_Temperaturen",
		name: "Saugstatus Verdampfer Temperatur",
		role: "value.temperature",
		type: "number",
		unit: "°C",
		dataSource: "value",
	},

	// Eingänge
	ASDin: {
		folder: "Informationen.02_Eingaenge",
		name: "Abtau-Endeschalter ASD",
		role: "value",
		type: "number",
		states: { 0: "Aus", 1: "Ein" },
		dataSource: "value",
	},
	EVUin: {
		folder: "Informationen.02_Eingaenge",
		name: "EVU-Sperre",
		role: "value",
		type: "number",
		states: { 0: "Aus", 1: "Ein" },
		dataSource: "value",
	},
	HDin: {
		folder: "Informationen.02_Eingaenge",
		name: "Hochdruckwächter HD",
		role: "value",
		type: "number",
		states: { 0: "Aus", 1: "Ein" },
		dataSource: "value",
	},
	MOTin: {
		folder: "Informationen.02_Eingaenge",
		name: "Motorschutz MOT",
		role: "value",
		type: "number",
		states: { 0: "Aus", 1: "Ein" },
		dataSource: "value",
	},
	NDin: {
		folder: "Informationen.02_Eingaenge",
		name: "Niederdruckwächter ND",
		role: "value",
		type: "number",
		states: { 0: "Aus", 1: "Ein" },
		dataSource: "value",
	},
	AnalogIn: {
		folder: "Informationen.02_Eingaenge",
		name: "Analoger Eingang 1",
		role: "value",
		type: "number",
		unit: "V",
		dataSource: "value",
	},
	NDin_pressure: {
		folder: "Informationen.02_Eingaenge",
		name: "Niederdruck-Sensorwert",
		role: "value.pressure",
		type: "number",
		unit: "bar",
		factor: 1,
		dataSource: "value",
	},
	HDin_pressure: {
		folder: "Informationen.02_Eingaenge",
		name: "Hochdruck-Sensorwert",
		role: "value.pressure",
		type: "number",
		unit: "bar",
		factor: 1,
		dataSource: "value",
	},
	BWTin: {
		folder: "Informationen.02_Eingaenge",
		name: "Brauchwasserthermostat BWT",
		role: "value",
		type: "number",
		states: { 0: "Aus", 1: "Ein" },
		dataSource: "value",
	},

	// Ausgänge
	AVout: {
		folder: "Informationen.03_Ausgaenge",
		name: "Abtauventil AV",
		role: "value",
		type: "number",
		states: { 0: "Aus", 1: "Ein" },
		dataSource: "value",
	},
	BUPout: {
		folder: "Informationen.03_Ausgaenge",
		name: "Warmwasser-Umwälzpumpe BUP",
		role: "value",
		type: "number",
		states: { 0: "Aus", 1: "Ein" },
		dataSource: "value",
	},
	HUPout: {
		folder: "Informationen.03_Ausgaenge",
		name: "Heizungsumwälzpumpe HUP",
		role: "value",
		type: "number",
		states: { 0: "Aus", 1: "Ein" },
		dataSource: "value",
	},
	VENout: {
		folder: "Informationen.03_Ausgaenge",
		name: "Ventilator VEN",
		role: "value",
		type: "number",
		states: { 0: "Aus", 1: "Ein" },
		dataSource: "value",
	},
	VD1out: {
		folder: "Informationen.03_Ausgaenge",
		name: "Verdichter 1 VD1",
		role: "value",
		type: "number",
		states: { 0: "Aus", 1: "Ein" },
		dataSource: "value",
	},
	ZIPout: {
		folder: "Informationen.03_Ausgaenge",
		name: "Zirkulationspumpe ZIP",
		role: "value",
		type: "number",
		states: { 0: "Aus", 1: "Ein" },
		dataSource: "value",
	},
	ZUPout: {
		folder: "Informationen.03_Ausgaenge",
		name: "Zusatzumwälzpumpe ZUP",
		role: "value",
		type: "number",
		states: { 0: "Aus", 1: "Ein" },
		dataSource: "value",
	},
	ZW1out: {
		folder: "Informationen.03_Ausgaenge",
		name: "Zweiter Wärmeerzeuger 1 ZW1",
		role: "value",
		type: "number",
		states: { 0: "Aus", 1: "Ein" },
		dataSource: "value",
	},
	analogOut1: {
		folder: "Informationen.03_Ausgaenge",
		name: "Analoger Ausgang 1",
		role: "value",
		type: "number",
		unit: "V",
		dataSource: "value",
		factor: 100,
	},
	analogOut2: {
		folder: "Informationen.03_Ausgaenge",
		name: "Analoger Ausgang 2",
		role: "value",
		type: "number",
		unit: "V",
		dataSource: "value",
		factor: 100,
	},
	defrostValve: {
		folder: "Informationen.03_Ausgaenge",
		name: "Status Abtauventil",
		role: "value",
		type: "number",
		states: { 0: "Aus", 1: "Ein" },
		dataSource: "value",
	},
	hotWaterBoilerValve: {
		folder: "Informationen.03_Ausgaenge",
		name: "Status Umschaltventil Warmwasser",
		role: "value",
		type: "number",
		states: { 0: "Aus", 1: "Ein" },
		dataSource: "value",
	},
	heatingSystemCircPump: {
		folder: "Informationen.03_Ausgaenge",
		name: "Heizungssystem Zirkulationspumpe Laufindikator",
		role: "indicator",
		type: "boolean",
		dataSource: "value",
	},
	heatSourceMotor: {
		folder: "Informationen.03_Ausgaenge",
		name: "Motor Wärmequelle",
		role: "value",
		type: "number",
		states: { 0: "Aus", 1: "Ein" },
		dataSource: "value",
	},
	compressor1: {
		folder: "Informationen.03_Ausgaenge",
		name: "Status Kompressor 1 Laufrückmeldung",
		role: "value",
		type: "number",
		states: { 0: "Aus", 1: "Ein" },
		dataSource: "value",
	},
	hotWaterCircPumpExtern: {
		folder: "Informationen.03_Ausgaenge",
		name: "Warmwasser Zirkulationspumpe Extern",
		role: "value",
		type: "number",
		states: { 0: "Aus", 1: "Ein" },
		dataSource: "value",
	},

	// Zeiten
	Time_WPein_akt: {
		folder: "Informationen.04_Timer",
		name: "Aktuelle Einschaltzeit Wärmepumpe",
		role: "value",
		type: "number",
		unit: "s",
		dataSource: "value",
	},
	Time_ZWE1_akt: {
		folder: "Informationen.04_Timer",
		name: "Aktuelle Laufzeit ZWE1",
		role: "value",
		type: "number",
		unit: "s",
		dataSource: "value",
	},
	Timer_EinschVerz: {
		folder: "Informationen.04_Timer",
		name: "Einschaltverzögerung Restzeit",
		role: "value",
		type: "number",
		unit: "s",
		dataSource: "value",
	},
	Time_SSPAUS_akt: {
		folder: "Informationen.04_Timer",
		name: "Aktuelle Sperrzeit AUS",
		role: "value",
		type: "number",
		unit: "s",
		dataSource: "value",
	},
	Time_SSPEIN_akt: {
		folder: "Informationen.04_Timer",
		name: "Aktuelle Sperrzeit EIN",
		role: "value",
		type: "number",
		unit: "s",
		dataSource: "value",
	},
	Time_VDStd_akt: {
		folder: "Informationen.04_Timer",
		name: "Aktuelle Standzeit Verdichter",
		role: "value",
		type: "number",
		unit: "s",
		dataSource: "value",
	},
	Time_HRM_akt: {
		folder: "Informationen.04_Timer",
		name: "Aktuelle Zeit HRM",
		role: "value",
		type: "number",
		unit: "s",
		dataSource: "value",
	},
	Time_HRW_akt: {
		folder: "Informationen.04_Timer",
		name: "Aktuelle Zeit HRW",
		role: "value",
		type: "number",
		unit: "s",
		dataSource: "value",
	},
	Time_Heissgas: {
		folder: "Informationen.04_Timer",
		name: "Zeit Heißgasüberwachung",
		role: "value",
		type: "number",
		unit: "s",
		dataSource: "value",
	},
	ahp_Zeit: {
		folder: "Informationen.04_Timer",
		name: "Zeit ahp-Stufe",
		role: "value",
		type: "number",
		unit: "s",
		dataSource: "value",
	},

	// Betriebsstunden
	hours_compressor1: {
		folder: "Informationen.05_Betriebsstunden",
		name: "Betriebsstunden Kompressor 1",
		role: "value",
		type: "number",
		unit: "h",
		dataSource: "value",
	},
	starts_compressor1: {
		folder: "Informationen.05_Betriebsstunden",
		name: "Schaltspiele Kompressor 1",
		role: "value",
		type: "number",
		dataSource: "value",
	},
	hours_2nd_heat_source1: {
		folder: "Informationen.05_Betriebsstunden",
		name: "Betriebsstunden Zweiter Wärmeerzeuger 1 (Heizstab)",
		role: "value",
		type: "number",
		unit: "h",
		dataSource: "value",
	},
	hours_heatpump: {
		folder: "Informationen.05_Betriebsstunden",
		name: "Betriebsstunden Wärmepumpe Gesamt",
		role: "value",
		type: "number",
		unit: "h",
		dataSource: "value",
	},
	hours_heating: {
		folder: "Informationen.05_Betriebsstunden",
		name: "Betriebsstunden Heizbetrieb",
		role: "value",
		type: "number",
		unit: "h",
		dataSource: "value",
	},
	hours_warmwater: {
		folder: "Informationen.05_Betriebsstunden",
		name: "Betriebsstunden Warmwassererzeugung",
		role: "value",
		type: "number",
		unit: "h",
		dataSource: "value",
	},

	// Fehlerspeicher
	Fehlerspeicher: {
		folder: "Informationen.06_Fehlerspeicher",
		name: "Fehlerhistorie (Die letzten 5 Fehler)",
		role: "string",
		type: "json",
		isVirtual: true,
	},

	// Abschaltungen
	Abschaltungen: {
		folder: "Informationen.07_Abschaltungen",
		name: "Abschalthistorie (Die letzten 5 Abschaltungen)",
		role: "string",
		type: "json",
		isVirtual: true,
	},

	// Betriebszustand
	WP_BZ_akt: {
		folder: "Informationen.08_Betriebszustand",
		name: "Aktueller Betriebszustand Code",
		role: "value",
		type: "number",
		states: {
			0: "Heizbetrieb",
			1: "Trinkwarmwasser",
			2: "Schwimmbad",
			3: "EVU-Sperre",
			4: "Abtauen",
			5: "Leerlauf",
			6: "Externe Energiequelle",
			7: "Kühlung",
		},
		dataSource: "value",
	},
	heatpump_extendet_state_string: {
		folder: "Informationen.08_Betriebszustand",
		name: "Erweiterter Status Text",
		role: "text",
		type: "string",
		dataSource: "value",
	},
	opStateHeating: {
		folder: "Informationen.08_Betriebszustand",
		name: "Betriebszustand Heizung",
		role: "value",
		type: "number",
		states: { 0: "Abgesenkt", 1: "Normal", 2: "Heizgrenze", 3: "Aus", 4: "Frostschutz" },
		dataSource: "value",
	},
	opStateHeatingString: {
		folder: "Informationen.08_Betriebszustand",
		name: "Betriebszustand Heizung",
		role: "text",
		type: "string",
		dataSource: "value",
	},
	opStateHotWaterString: {
		folder: "Informationen.08_Betriebszustand",
		name: "Betriebszustand Warmwasser",
		role: "text",
		type: "string",
		dataSource: "value",
	},
	bivalentLevel: {
		folder: "Informationen.08_Betriebszustand",
		name: "Bivalenzstufe",
		role: "value",
		type: "number",
		states: {
			1: "Ein Verdichter darf laufen",
			2: "Zwei Verdichter dürfen laufen",
			3: "Zusätzlicher Wärmeerzeuger darf mitlaufen",
		},
		dataSource: "value",
	},
	heatpump_duration: {
		folder: "Informationen.08_Betriebszustand",
		name: "Dauer aktueller Zustand",
		role: "value",
		type: "number",
		unit: "s",
		dataSource: "value",
	},
	heatpump_state_string: {
		folder: "Informationen.08_Betriebszustand",
		name: "Wärmepumpen Status Text",
		role: "text",
		type: "string",
		dataSource: "value",
	},
	Heizen_nach_Wasser: {
		folder: "Informationen.08_Betriebszustand",
		name: "Heizen nach Wasser aktiv",
		role: "switch",
		type: "boolean",
		isVirtual: true,
	},

	// Wärmemenge
	thermalenergy_heating: {
		folder: "Informationen.09_Wärmemenge",
		name: "Wärmemenge Heizung Erzeugt",
		role: "value.power.consumption",
		type: "number",
		unit: "kWh",
		dataSource: "value",
	},
	thermalenergy_warmwater: {
		folder: "Informationen.09_Wärmemenge",
		name: "Wärmemenge Warmwasser Erzeugt",
		role: "value.power.consumption",
		type: "number",
		unit: "kWh",
		dataSource: "value",
	},
	thermalenergy_ZWE1: {
		folder: "Informationen.09_Wärmemenge",
		name: "Wärmemenge Heizstab Erzeugt",
		role: "value.power.consumption",
		type: "number",
		luxWriteId: "1059",
		unit: "kWh",
		dataSource: "raw_parameter", // <--- HIER DER WECHSEL ZU 3003!
		factor: 100,
	},
	thermalenergy_total: {
		folder: "Informationen.09_Wärmemenge",
		name: "Wärmemenge Gesamt Erzeugt",
		role: "value.power.consumption",
		type: "number",
		unit: "kWh",
		dataSource: "value",
	},

	// Energie
	energy_heating: {
		folder: "Informationen.10_Engergie",
		name: "Energie Heizung Erzeugt",
		role: "value.power.consumption",
		luxWriteId: "1136",
		type: "number",
		unit: "kWh",
		dataSource: "raw_parameter", // <--- HIER DER WECHSEL ZU 3003!
		factor: 100,
	},
	energy_warmwater: {
		folder: "Informationen.10_Engergie",
		name: "Energie Warmwasser Erzeugt",
		role: "value.power.consumption",
		type: "number",
		luxWriteId: "1137",
		unit: "kWh",
		dataSource: "raw_parameter", // <--- HIER DER WECHSEL ZU 3003!
		factor: 100,
	},
	energy_ZWE1: {
		folder: "Informationen.10_Engergie",
		name: "Energie Heizstab Erzeugt",
		role: "value.power.consumption",
		type: "number",
		luxWriteId: "1059",
		unit: "kWh",
		dataSource: "raw_parameter", // <--- HIER DER WECHSEL ZU 3003!
		factor: 100,
	},
	energy_total: {
		folder: "Informationen.10_Engergie",
		name: "Energie Gesamt Erzeugt",
		role: "value.power.consumption",
		type: "number",
		unit: "kWh",
		isVirtual: true, // <--- KORREKTUR: Fehlte! Wird vom Adapter selbst addiert.
	},

	// 11_Tabellen

	heatingOperationTimerTable52MonFri: {
		folder: "Informationen.11_Tabellen.Heizen",
		name: "Heizbetrieb Timer Tabelle Mo-Fr (5+2)",
		role: "string",
		type: "json",
		dataSource: "parameter",
	},

	heatingOperationTimerTable52SatSun: {
		folder: "Informationen.11_Tabellen.Heizen",
		name: "Heizbetrieb Timer Tabelle Sa-So (5+2)",
		role: "string",
		type: "json",
		dataSource: "parameter",
	},

	heatingOperationTimerTableDayFriday: {
		folder: "Informationen.11_Tabellen.Heizen",
		name: "Heizbetrieb Timer Tabelle Fr (Day Friday)",
		role: "string",
		type: "json",
		dataSource: "parameter",
	},

	heatingOperationTimerTableDayMonday: {
		folder: "Informationen.11_Tabellen.Heizen",
		name: "Heizbetrieb Timer Tabelle Mo (Day Monday)",
		role: "string",
		type: "json",
		dataSource: "parameter",
	},

	heatingOperationTimerTableDaySaturday: {
		folder: "Informationen.11_Tabellen.Heizen",
		name: "Heizbetrieb Timer Tabelle Sa (Day Saturday)",
		role: "string",
		type: "json",
		dataSource: "parameter",
	},

	heatingOperationTimerTableDaySunday: {
		folder: "Informationen.11_Tabellen.Heizen",
		name: "Heizbetrieb Timer Tabelle So (Day Sunday)",
		role: "string",
		type: "json",
		dataSource: "parameter",
	},

	heatingOperationTimerTableDayThursday: {
		folder: "Informationen.11_Tabellen.Heizen",
		name: "Heizbetrieb Timer Tabelle Do (Day Thursday)",
		role: "string",
		type: "json",
		dataSource: "parameter",
	},

	heatingOperationTimerTableDayTuesday: {
		folder: "Informationen.11_Tabellen.Heizen",
		name: "Heizbetrieb Timer Tabelle Di (Day Tuesday)",
		role: "string",
		type: "json",
		dataSource: "parameter",
	},

	heatingOperationTimerTableDayWednesday: {
		folder: "Informationen.11_Tabellen.Heizen",
		name: "Heizbetrieb Timer Tabelle Mi (Day Wednesday)",
		role: "string",
		type: "json",
		dataSource: "parameter",
	},

	heatingOperationTimerTableWeek: {
		folder: "Informationen.11_Tabellen.Heizen",
		name: "Heizbetrieb Timer Tabelle Wo (Day Week)",
		role: "string",
		type: "json",
		dataSource: "parameter",
	},

	hotWaterCircPumpTimerTable52MonFri: {
		folder: "Informationen.11_Tabellen.Warmwasser",
		name: "Warmwasserbetrieb Timer Tabelle Mo-Fr (5+2)",
		role: "string",
		type: "json",
		dataSource: "parameter",
	},

	hotWaterCircPumpTimerTable52SatSun: {
		folder: "Informationen.11_Tabellen.Warmwasser",
		name: "Warmwasserbetrieb Timer Tabelle Sa-So (5+2)",
		role: "string",
		type: "json",
		dataSource: "parameter",
	},

	hotWaterCircPumpTimerTableDayFriday: {
		folder: "Informationen.11_Tabellen.Warmwasser",
		name: "Warmwasserbetrieb Timer Tabelle Fr (Day Friday)",
		role: "string",
		type: "json",
		dataSource: "parameter",
	},

	hotWaterCircPumpTimerTableDayMonday: {
		folder: "Informationen.11_Tabellen.Warmwasser",
		name: "Warmwasserbetrieb Timer Tabelle Mo (Day Monday)",
		role: "string",
		type: "json",
		dataSource: "parameter",
	},

	hotWaterCircPumpTimerTableDaySaturday: {
		folder: "Informationen.11_Tabellen.Warmwasser",
		name: "Warmwasserbetrieb Timer Tabelle Sa (Day Saturday)",
		role: "string",
		type: "json",
		dataSource: "parameter",
	},

	hotWaterCircPumpTimerTableDaySunday: {
		folder: "Informationen.11_Tabellen.Warmwasser",
		name: "Warmwasserbetrieb Timer Tabelle So (Day Sunday)",
		role: "string",
		type: "json",
		dataSource: "parameter",
	},

	hotWaterCircPumpTimerTableDayThursday: {
		folder: "Informationen.11_Tabellen.Warmwasser",
		name: "Warmwasserbetrieb Timer Tabelle Do (Day Thursday)",
		role: "string",
		type: "json",
		dataSource: "parameter",
	},

	hotWaterCircPumpTimerTableDayTuesday: {
		folder: "Informationen.11_Tabellen.Warmwasser",
		name: "Warmwasserbetrieb Timer Tabelle Di (Day Tuesday)",
		role: "string",
		type: "json",
		dataSource: "parameter",
	},

	hotWaterCircPumpTimerTableDayWednesday: {
		folder: "Informationen.11_Tabellen.Warmwasser",
		name: "Warmwasserbetrieb Timer Tabelle Mi (Day Wednesday)",
		role: "string",
		type: "json",
		dataSource: "parameter",
	},

	hotWaterCircPumpTimerTableWeek: {
		folder: "Informationen.11_Tabellen.Warmwasser",
		name: "Warmwasserbetrieb Timer Tabelle Wo (Day Week)",
		role: "string",
		type: "json",
		dataSource: "parameter",
	},

	// 12_Systeminfo
	typeHeatpump: {
		folder: "Informationen.12_Systeminfo",
		name: "Wärmepumpen-Typ",
		role: "text",
		type: "string",
		dataSource: "value",
	},
	firmware: {
		folder: "Informationen.12_Systeminfo",
		name: "Firmware-Version",
		role: "text",
		type: "string",
		dataSource: "value",
	},
	AdresseIP_akt: {
		folder: "Informationen.12_Systeminfo",
		name: "Aktuelle IP-Adresse",
		role: "info.ip",
		type: "string",
		dataSource: "value",
	},
	SubNetMask_akt: {
		folder: "Informationen.12_Systeminfo",
		name: "Subnetzmaske",
		role: "info.ip",
		type: "string",
		dataSource: "value",
	},
	Add_Broadcast: {
		folder: "Informationen.12_Systeminfo",
		name: "Broadcast-Adresse",
		role: "info.ip",
		type: "string",
		dataSource: "value",
	},
	Add_StdGateway: {
		folder: "Informationen.12_Systeminfo",
		name: "Standard-Gateway",
		role: "info.ip",
		type: "string",
		dataSource: "value",
	},
	LIN_exists: {
		folder: "Informationen.12_Systeminfo",
		name: "LIN-Bus vorhanden",
		role: "indicator",
		type: "boolean",
		dataSource: "value",
	},
	rawDeviceTimeCalc: {
		folder: "Informationen.12_Systeminfo",
		name: "Berechnete Gerätezeit",
		role: "date",
		type: "string",
		dataSource: "value",
	},
	// ==========================================
	// EINSTELLUNGEN & PARAMETER (Beschreibbar)
	// ==========================================
	//Betriebsmodus
	heating_operation_mode: {
		folder: "Einstellungen.01_Betriebsmodus",
		name: "Betriebsart Heizung",
		role: "level.mode",
		type: "number",
		write: true,
		states: { 0: "Automatik", 1: "Zweites WEZ", 2: "Party", 3: "Ferien", 4: "Aus" },
		dataSource: "parameter",
	},
	warmwater_operation_mode: {
		folder: "Einstellungen.01_Betriebsmodus",
		name: "Betriebsart Warmwasser",
		role: "level.mode",
		type: "number",
		write: true,
		states: { 0: "Automatik", 1: "Zweites WEZ", 2: "Party", 3: "Ferien", 4: "Aus" },
		dataSource: "parameter",
	},

	//Heizung
	heating_curve_end_point: {
		folder: "Einstellungen.02_Heizung",
		name: "Heizkurve Endpunkt (Rücklauf)",
		role: "value.temperature",
		type: "number",
		unit: "°C",
		write: true,
		min: 20,
		max: 45,
		dataSource: "parameter",
	},
	heating_curve_parallel_offset: {
		folder: "Einstellungen.02_Heizung",
		name: "Heizkurve Fusspunkt",
		role: "value.temperature",
		type: "number",
		unit: "°C",
		write: true,
		min: 20,
		max: 45,
		dataSource: "parameter",
	},
	deltaHeatingReduction: {
		folder: "Einstellungen.02_Heizung",
		name: "Heizung Nachtabsenkung (Delta)",
		role: "value.temperature",
		type: "number",
		unit: "K",
		write: true,
		factor: 10,
		min: -10,
		max: 10,
		dataSource: "parameter",
	},
	heating_temperature: {
		folder: "Einstellungen.02_Heizung",
		name: "Heizung Verschiebng Soll-Temperatur (Wunschwert)",
		role: "value.temperature",
		type: "number",
		unit: "°C",
		write: true,
		luxWriteId: "heating_target_temperature",
		min: -5,
		max: 5,
		dataSource: "parameter",
	},
	returnTemperatureHysteresis: {
		folder: "Einstellungen.02_Heizung",
		name: "Rücklauftemperatur Hysterese",
		role: "value.temperature",
		type: "number",
		unit: "K",
		write: true,
		factor: 1,
		min: 1,
		max: 5,
		dataSource: "parameter",
	},
	thresholdHeatingLimit: {
		folder: "Einstellungen.02_Heizung",
		name: "Parameter 700 (ID_Einst_Heizgrenze_Temp)",
		role: "value",
		type: "number",
		write: true,
		luxWriteId: "700",
		unit: "°C",
		factor: 10,
		dataSource: "raw_parameter",
	},
	heatingLimit: {
		folder: "Einstellungen.02_Heizung",
		name: "Parameter 699 (ID_Einst_Heizgrenze)",
		write: true,
		role: "value",
		type: "number",
		luxWriteId: "699",
		states: { 0: "Aus", 1: "Ein" },
		dataSource: "raw_parameter",
	},

	// Warmwasser
	warmwater_temperature: {
		folder: "Einstellungen.03_Warmwasser",
		name: "Warmwasser Soll-Temperatur",
		role: "value.temperature",
		type: "number",
		unit: "°C",
		write: true,
		luxWriteId: "temperature_hot_water_target",
		min: 30,
		max: 65,
		dataSource: "parameter",
	},
	hotWaterTemperatureHysteresis: {
		folder: "Einstellungen.03_Warmwasser",
		name: "Warmwasser Hysterese",
		role: "value.temperature",
		type: "number",
		unit: "K",
		write: true,
		factor: 1,
		min: 1,
		max: 15,
		dataSource: "parameter",
	},
	heating_system_circ_pump_voltage_nominal: {
		folder: "Einstellungen.04_HUP",
		name: "Heizungsumwälzpumpe Nennspannung",
		role: "value.voltage",
		type: "number",
		unit: "V",
		write: true,
		factor: 1,
		min: 3,
		max: 10,
		dataSource: "parameter",
	},
	heating_system_circ_pump_voltage_minimal: {
		folder: "Einstellungen.04_HUP",
		name: "Heizungsumwälzpumpe Minimalspannung",
		role: "value.voltage",
		type: "number",
		unit: "V",
		write: true,
		factor: 1,
		min: 3,
		max: 10,
		dataSource: "parameter",
	},

	//Zip
	runDeaerate: {
		folder: "Einstellungen.05_ZIP",
		name: "Entlüftungsprogramm starten",
		role: "indicator",
		type: "boolean",
		write: true,
		states: { 0: "Aus", 1: "Ein" },
		dataSource: "parameter",
	},
	hotWaterCircPumpDeaerate: {
		folder: "Einstellungen.05_ZIP",
		name: "Zirkulationspumpe entlüften",
		role: "value",
		type: "number",
		states: { 0: "Aus", 1: "Ein" },
		write: true,
		dataSource: "parameter",
	},
	Activate_Zip: {
		folder: "Einstellungen.05_ZIP",
		name: "Makro: ZIP Entlüftung starten",
		role: "switch",
		type: "boolean",
		write: true,
		states: { 0: "Aus", 1: "Ein" },
		luxWriteId: "Activate_Zip",
		isVirtual: true,
	},
	hotWaterCircPumpOnTime: {
		folder: "Einstellungen.05_ZIP",
		name: "Laufzeit ZIP aktiv",
		role: "value",
		type: "number",
		write: true,
		unit: "min",
		factor: 1,
		dataSource: "parameter",
	},
	hotWaterCircPumpOffTime: {
		folder: "Einstellungen.05_ZIP",
		name: "Laufzeit ZIP inaktiv",
		role: "value",
		type: "number",
		write: true,
		unit: "min",
		factor: 1,
		dataSource: "parameter",
	},
	zip_aktiv: {
		folder: "Einstellungen.05_ZIP",
		name: "ZIP Dauer (Normal)",
		role: "value",
		type: "number",
		unit: "s",
		isVirtual: true,
		write: true,
		def: 120,
	},
	//Systemeinstellungen
	Pumpenoptimierung: {
		folder: "Einstellungen.06_System-Einstellung",
		name: "Parameter 49 (ID_Einst_Popt_akt)",
		role: "value",
		type: "number",
		write: true,
		luxWriteId: "49",
		dataSource: "raw_parameter",
		states: { 0: "Aus", 1: "Ein" },
	},

	Pumpen_Nachlauf: {
		folder: "Einstellungen.06_System-Einstellung",
		name: "Parameter 864 (ID_Einst_Popt_Nachlauf_akt)",
		role: "value",
		type: "number",
		write: true,
		luxWriteId: "864",
		dataSource: "raw_parameter",
		unit: "°C",
		factor: 1,
	},

	//Timer Table
	heatingOperationTimerTableSelected: {
		folder: "Einstellungen.07_Tabellen",
		name: "Aktuell ausgewählte Tabelle Heizbetrieb Timer",
		role: "value",
		type: "number",
		dataSource: "parameter",
		states: { 0: "Woche (Mo-So)", 1: "5+2 (Mo-Fr, Sa-So)", 2: "Tage (Mo, Di, ...)" },
	},
	hotWaterCircPumpTimerTableSelected: {
		folder: "Einstellungen.07_Tabellen",
		name: "Aktuell ausgewählte Tabelle Warmwasserbetrieb Timer",
		role: "value",
		type: "number",
		dataSource: "parameter",
		states: { 0: "Woche (Mo-So)", 1: "5+2 (Mo-Fr, Sa-So)", 2: "Tage (Mo, Di, ...)" },
	},

	// =========================================================
	// HEIZEN TIMER: WOCHE (MO-SO)
	// Basis: 223
	// =========================================================
	HZ_MoSo_Start1: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Mo-So",
		name: "Heizen Timer Tabelle Start 1 Woche (Mo-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "223",
		write: true,
	},
	HZ_MoSo_End1: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Mo-So",
		name: "Heizen Timer Tabelle Ende 1 Woche (Mo-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "224",
		write: true,
	},
	HZ_MoSo_Start2: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Mo-So",
		name: "Heizen Timer Tabelle Start 2 Woche (Mo-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "225",
		write: true,
	},
	HZ_MoSo_End2: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Mo-So",
		name: "Heizen Timer Tabelle Ende 2 Woche (Mo-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "226",
		write: true,
	},
	HZ_MoSo_Start3: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Mo-So",
		name: "Heizen Timer Tabelle Start 3 Woche (Mo-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "227",
		write: true,
	},
	HZ_MoSo_End3: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Mo-So",
		name: "Heizen Timer Tabelle Ende 3 Woche (Mo-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "228",
		write: true,
	},

	// =========================================================
	// HEIZEN TIMER: 5+2 (MO-FR & SA-SO)
	// =========================================================
	HZ_MoFr_Start1: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.52_MoFr_SaSo",
		name: "Heizen Timer Tabelle Start 1 (Mo-Fr)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "229",
		write: true,
	},
	HZ_MoFr_Ende1: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.52_MoFr_SaSo",
		name: "Heizen Timer Tabelle Ende 1 (Mo-Fr)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "230",
		write: true,
	},
	HZ_MoFr_Start2: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.52_MoFr_SaSo",
		name: "Heizen Timer Tabelle Start 2 (Mo-Fr)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "231",
		write: true,
	},
	HZ_MoFr_Ende2: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.52_MoFr_SaSo",
		name: "Heizen Timer Tabelle Ende 2 (Mo-Fr)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "232",
		write: true,
	},
	HZ_MoFr_Start3: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.52_MoFr_SaSo",
		name: "Heizen Timer Tabelle Start 3 (Mo-Fr)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "233",
		write: true,
	},
	HZ_MoFr_Ende3: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.52_MoFr_SaSo",
		name: "Heizen Timer Tabelle Ende 3 (Mo-Fr)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "234",
		write: true,
	},
	HZ_SaSo_Start1: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.52_MoFr_SaSo",
		name: "Heizen Timer Tabelle Start 1 (Sa-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "235",
		write: true,
	},
	HZ_SaSo_Ende1: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.52_MoFr_SaSo",
		name: "Heizen Timer Tabelle Ende 1 (Sa-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "236",
		write: true,
	},
	HZ_SaSo_Start2: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.52_MoFr_SaSo",
		name: "Heizen Timer Tabelle Start 2 (Sa-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "237",
		write: true,
	},
	HZ_SaSo_Ende2: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.52_MoFr_SaSo",
		name: "Heizen Timer Tabelle Ende 2 (Sa-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "238",
		write: true,
	},
	HZ_SaSo_Start3: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.52_MoFr_SaSo",
		name: "Heizen Timer Tabelle Start 3 (Sa-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "239",
		write: true,
	},
	HZ_SaSo_Ende3: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.52_MoFr_SaSo",
		name: "Heizen Timer Tabelle Ende 3 (Sa-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "240",
		write: true,
	},

	// =========================================================
	// HEIZEN TIMER: EINZELTAGE
	// =========================================================
	HZ_Sonntag_Start1: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Sonntag",
		name: "Heizen Timer Tabelle Start 1 Sonntag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "241",
		write: true,
	},
	HZ_Sonntag_Ende1: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Sonntag",
		name: "Heizen Timer Tabelle Ende 1 Sonntag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "242",
		write: true,
	},
	HZ_Sonntag_Start2: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Sonntag",
		name: "Heizen Timer Tabelle Start 2 Sonntag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "243",
		write: true,
	},
	HZ_Sonntag_Ende2: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Sonntag",
		name: "Heizen Timer Tabelle Ende 2 Sonntag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "244",
		write: true,
	},
	HZ_Sonntag_Start3: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Sonntag",
		name: "Heizen Timer Tabelle Start 3 Sonntag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "245",
		write: true,
	},
	HZ_Sonntag_Ende3: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Sonntag",
		name: "Heizen Timer Tabelle Ende 3 Sonntag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "246",
		write: true,
	},
	HZ_Montag_Start1: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Montag",
		name: "Heizen Timer Tabelle Start 1 Montag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "247",
		write: true,
	},
	HZ_Montag_Ende1: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Montag",
		name: "Heizen Timer Tabelle Ende 1 Montag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "248",
		write: true,
	},
	HZ_Montag_Start2: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Montag",
		name: "Heizen Timer Tabelle Start 2 Montag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "249",
		write: true,
	},
	HZ_Montag_Ende2: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Montag",
		name: "Heizen Timer Tabelle Ende 2 Montag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "250",
		write: true,
	},
	HZ_Montag_Start3: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Montag",
		name: "Heizen Timer Tabelle Start 3 Montag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "251",
		write: true,
	},
	HZ_Montag_Ende3: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Montag",
		name: "Heizen Timer Tabelle Ende 3 Montag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "252",
		write: true,
	},
	HZ_Dienstag_Start1: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Dienstag",
		name: "Heizen Timer Tabelle Start 1 Dienstag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "253",
		write: true,
	},
	HZ_Dienstag_Ende1: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Dienstag",
		name: "Heizen Timer Tabelle Ende 1 Dienstag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "254",
		write: true,
	},
	HZ_Dienstag_Start2: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Dienstag",
		name: "Heizen Timer Tabelle Start 2 Dienstag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "255",
		write: true,
	},
	HZ_Dienstag_Ende2: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Dienstag",
		name: "Heizen Timer Tabelle Ende 2 Dienstag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "256",
		write: true,
	},
	HZ_Dienstag_Start3: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Dienstag",
		name: "Heizen Timer Tabelle Start 3 Dienstag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "257",
		write: true,
	},
	HZ_Dienstag_Ende3: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Dienstag",
		name: "Heizen Timer Tabelle Ende 3 Dienstag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "258",
		write: true,
	},
	HZ_Mittwoch_Start1: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Mittwoch",
		name: "Heizen Timer Tabelle Start 1 Mittwoch",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "259",
		write: true,
	},
	HZ_Mittwoch_Ende1: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Mittwoch",
		name: "Heizen Timer Tabelle Ende 1 Mittwoch",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "260",
		write: true,
	},
	HZ_Mittwoch_Start2: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Mittwoch",
		name: "Heizen Timer Tabelle Start 2 Mittwoch",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "261",
		write: true,
	},
	HZ_Mittwoch_Ende2: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Mittwoch",
		name: "Heizen Timer Tabelle Ende 2 Mittwoch",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "262",
		write: true,
	},
	HZ_Mittwoch_Start3: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Mittwoch",
		name: "Heizen Timer Tabelle Start 3 Mittwoch",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "263",
		write: true,
	},
	HZ_Mittwoch_Ende3: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Mittwoch",
		name: "Heizen Timer Tabelle Ende 3 Mittwoch",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "264",
		write: true,
	},
	HZ_Donnerstag_Start1: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Donnerstag",
		name: "Heizen Timer Tabelle Start 1 Donnerstag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "265",
		write: true,
	},
	HZ_Donnerstag_Ende1: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Donnerstag",
		name: "Heizen Timer Tabelle Ende 1 Donnerstag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "266",
		write: true,
	},
	HZ_Donnerstag_Start2: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Donnerstag",
		name: "Heizen Timer Tabelle Start 2 Donnerstag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "267",
		write: true,
	},
	HZ_Donnerstag_Ende2: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Donnerstag",
		name: "Heizen Timer Tabelle Ende 2 Donnerstag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "268",
		write: true,
	},
	HZ_Donnerstag_Start3: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Donnerstag",
		name: "Heizen Timer Tabelle Start 3 Donnerstag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "269",
		write: true,
	},
	HZ_Donnerstag_Ende3: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Donnerstag",
		name: "Heizen Timer Tabelle Ende 3 Donnerstag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "270",
		write: true,
	},
	HZ_Freitag_Start1: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Freitag",
		name: "Heizen Timer Tabelle Start 1 Freitag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "271",
		write: true,
	},
	HZ_Freitag_Ende1: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Freitag",
		name: "Heizen Timer Tabelle Ende 1 Freitag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "272",
		write: true,
	},
	HZ_Freitag_Start2: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Freitag",
		name: "Heizen Timer Tabelle Start 2 Freitag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "273",
		write: true,
	},
	HZ_Freitag_Ende2: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Freitag",
		name: "Heizen Timer Tabelle Ende 2 Freitag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "274",
		write: true,
	},
	HZ_Freitag_Start3: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Freitag",
		name: "Heizen Timer Tabelle Start 3 Freitag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "275",
		write: true,
	},
	HZ_Freitag_Ende3: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Freitag",
		name: "Heizen Timer Tabelle Ende 3 Freitag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "276",
		write: true,
	},
	HZ_Samstag_Start1: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Samstag",
		name: "Heizen Timer Tabelle Start 1 Samstag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "277",
		write: true,
	},
	HZ_Samstag_Ende1: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Samstag",
		name: "Heizen Timer Tabelle Ende 1 Samstag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "278",
		write: true,
	},
	HZ_Samstag_Start2: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Samstag",
		name: "Heizen Timer Tabelle Start 2 Samstag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "279",
		write: true,
	},
	HZ_Samstag_Ende2: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Samstag",
		name: "Heizen Timer Tabelle Ende 2 Samstag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "280",
		write: true,
	},
	HZ_Samstag_Start3: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Samstag",
		name: "Heizen Timer Tabelle Start 3 Samstag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "281",
		write: true,
	},
	HZ_Samstag_Ende3: {
		folder: "Einstellungen.07_Tabellen.Heizen.Parameter.Days.Samstag",
		name: "Heizen Timer Tabelle Ende 3 Samstag",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "282",
		write: true,
	},

	// =========================================================
	// WARMWASSER TIMER: WOCHE (MO-SO)
	// Basis: 507 (5 Paare = 10 Indizes)
	// =========================================================
	WW_MoSo_Start1: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Mo-So",
		name: "Warmwasser Timer Start 1 (Mo-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "507",
		write: true,
	},
	WW_MoSo_End1: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Mo-So",
		name: "Warmwasser Timer Ende 1 (Mo-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "508",
		write: true,
	},
	WW_MoSo_Start2: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Mo-So",
		name: "Warmwasser Timer Start 2 (Mo-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "509",
		write: true,
	},
	WW_MoSo_End2: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Mo-So",
		name: "Warmwasser Timer Ende 2 (Mo-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "510",
		write: true,
	},
	WW_MoSo_Start3: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Mo-So",
		name: "Warmwasser Timer Start 3 (Mo-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "511",
		write: true,
	},
	WW_MoSo_End3: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Mo-So",
		name: "Warmwasser Timer Ende 3 (Mo-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "512",
		write: true,
	},
	WW_MoSo_Start4: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Mo-So",
		name: "Warmwasser Timer Start 4 (Mo-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "513",
		write: true,
	},
	WW_MoSo_End4: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Mo-So",
		name: "Warmwasser Timer Ende 4 (Mo-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "514",
		write: true,
	},
	WW_MoSo_Start5: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Mo-So",
		name: "Warmwasser Timer Start 5 (Mo-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "515",
		write: true,
	},
	WW_MoSo_End5: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Mo-So",
		name: "Warmwasser Timer Ende 5 (Mo-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "516",
		write: true,
	},

	// =========================================================
	// WARMWASSER TIMER: 5+2 (MO-FR & SA-SO)
	// =========================================================

	// --- MO-FR (Basis 517) ---
	WW_MoFr_Start1: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.52_MoFr_SaSo",
		name: "Warmwasser Timer Start 1 (Mo-Fr)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "517",
		write: true,
	},
	WW_MoFr_Ende1: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.52_MoFr_SaSo",
		name: "Warmwasser Timer Ende 1 (Mo-Fr)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "518",
		write: true,
	},
	WW_MoFr_Start2: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.52_MoFr_SaSo",
		name: "Warmwasser Timer Start 2 (Mo-Fr)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "519",
		write: true,
	},
	WW_MoFr_Ende2: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.52_MoFr_SaSo",
		name: "Warmwasser Timer Ende 2 (Mo-Fr)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "520",
		write: true,
	},
	WW_MoFr_Start3: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.52_MoFr_SaSo",
		name: "Warmwasser Timer Start 3 (Mo-Fr)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "521",
		write: true,
	},
	WW_MoFr_Ende3: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.52_MoFr_SaSo",
		name: "Warmwasser Timer Ende 3 (Mo-Fr)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "522",
		write: true,
	},
	WW_MoFr_Start4: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.52_MoFr_SaSo",
		name: "Warmwasser Timer Start 4 (Mo-Fr)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "523",
		write: true,
	},
	WW_MoFr_Ende4: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.52_MoFr_SaSo",
		name: "Warmwasser Timer Ende 4 (Mo-Fr)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "524",
		write: true,
	},
	WW_MoFr_Start5: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.52_MoFr_SaSo",
		name: "Warmwasser Timer Start 5 (Mo-Fr)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "525",
		write: true,
	},
	WW_MoFr_Ende5: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.52_MoFr_SaSo",
		name: "Warmwasser Timer Ende 5 (Mo-Fr)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "526",
		write: true,
	},

	// --- SA-SO (Basis 527) ---
	WW_SaSo_Start1: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.52_MoFr_SaSo",
		name: "Warmwasser Timer Start 1 (Sa-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "527",
		write: true,
	},
	WW_SaSo_Ende1: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.52_MoFr_SaSo",
		name: "Warmwasser Timer Ende 1 (Sa-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "528",
		write: true,
	},
	WW_SaSo_Start2: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.52_MoFr_SaSo",
		name: "Warmwasser Timer Start 2 (Sa-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "529",
		write: true,
	},
	WW_SaSo_Ende2: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.52_MoFr_SaSo",
		name: "Warmwasser Timer Ende 2 (Sa-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "530",
		write: true,
	},
	WW_SaSo_Start3: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.52_MoFr_SaSo",
		name: "Warmwasser Timer Start 3 (Sa-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "531",
		write: true,
	},
	WW_SaSo_Ende3: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.52_MoFr_SaSo",
		name: "Warmwasser Timer Ende 3 (Sa-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "532",
		write: true,
	},
	WW_SaSo_Start4: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.52_MoFr_SaSo",
		name: "Warmwasser Timer Start 4 (Sa-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "533",
		write: true,
	},
	WW_SaSo_Ende4: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.52_MoFr_SaSo",
		name: "Warmwasser Timer Ende 4 (Sa-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "534",
		write: true,
	},
	WW_SaSo_Start5: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.52_MoFr_SaSo",
		name: "Warmwasser Timer Start 5 (Sa-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "535",
		write: true,
	},
	WW_SaSo_Ende5: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.52_MoFr_SaSo",
		name: "Warmwasser Timer Ende 5 (Sa-So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "536",
		write: true,
	},

	// =========================================================
	// WARMWASSER TIMER: EINZELTAGE
	// =========================================================

	// --- SONNTAG (Basis 537) ---
	WW_Sonntag_Start1: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Sonntag",
		name: "Warmwasser Timer Start 1 (So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "537",
		write: true,
	},
	WW_Sonntag_Ende1: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Sonntag",
		name: "Warmwasser Timer Ende 1 (So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "538",
		write: true,
	},
	WW_Sonntag_Start2: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Sonntag",
		name: "Warmwasser Timer Start 2 (So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "539",
		write: true,
	},
	WW_Sonntag_Ende2: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Sonntag",
		name: "Warmwasser Timer Ende 2 (So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "540",
		write: true,
	},
	WW_Sonntag_Start3: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Sonntag",
		name: "Warmwasser Timer Start 3 (So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "541",
		write: true,
	},
	WW_Sonntag_Ende3: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Sonntag",
		name: "Warmwasser Timer Ende 3 (So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "542",
		write: true,
	},
	WW_Sonntag_Start4: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Sonntag",
		name: "Warmwasser Timer Start 4 (So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "543",
		write: true,
	},
	WW_Sonntag_Ende4: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Sonntag",
		name: "Warmwasser Timer Ende 4 (So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "544",
		write: true,
	},
	WW_Sonntag_Start5: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Sonntag",
		name: "Warmwasser Timer Start 5 (So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "545",
		write: true,
	},
	WW_Sonntag_Ende5: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Sonntag",
		name: "Warmwasser Timer Ende 5 (So)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "546",
		write: true,
	},

	// --- MONTAG (Basis 547) ---
	WW_Montag_Start1: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Montag",
		name: "Warmwasser Timer Start 1 (Mo)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "547",
		write: true,
	},
	WW_Montag_Ende1: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Montag",
		name: "Warmwasser Timer Ende 1 (Mo)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "548",
		write: true,
	},
	WW_Montag_Start2: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Montag",
		name: "Warmwasser Timer Start 2 (Mo)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "549",
		write: true,
	},
	WW_Montag_Ende2: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Montag",
		name: "Warmwasser Timer Ende 2 (Mo)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "550",
		write: true,
	},
	WW_Montag_Start3: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Montag",
		name: "Warmwasser Timer Start 3 (Mo)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "551",
		write: true,
	},
	WW_Montag_Ende3: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Montag",
		name: "Warmwasser Timer Ende 3 (Mo)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "552",
		write: true,
	},
	WW_Montag_Start4: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Montag",
		name: "Warmwasser Timer Start 4 (Mo)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "553",
		write: true,
	},
	WW_Montag_Ende4: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Montag",
		name: "Warmwasser Timer Ende 4 (Mo)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "554",
		write: true,
	},
	WW_Montag_Start5: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Montag",
		name: "Warmwasser Timer Start 5 (Mo)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "555",
		write: true,
	},
	WW_Montag_Ende5: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Montag",
		name: "Warmwasser Timer Ende 5 (Mo)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "556",
		write: true,
	},

	// --- DIENSTAG (Basis 557) ---
	WW_Dienstag_Start1: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Dienstag",
		name: "Warmwasser Timer Start 1 (Di)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "557",
		write: true,
	},
	WW_Dienstag_Ende1: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Dienstag",
		name: "Warmwasser Timer Ende 1 (Di)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "558",
		write: true,
	},
	WW_Dienstag_Start2: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Dienstag",
		name: "Warmwasser Timer Start 2 (Di)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "559",
		write: true,
	},
	WW_Dienstag_Ende2: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Dienstag",
		name: "Warmwasser Timer Ende 2 (Di)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "560",
		write: true,
	},
	WW_Dienstag_Start3: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Dienstag",
		name: "Warmwasser Timer Start 3 (Di)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "561",
		write: true,
	},
	WW_Dienstag_Ende3: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Dienstag",
		name: "Warmwasser Timer Ende 3 (Di)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "562",
		write: true,
	},
	WW_Dienstag_Start4: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Dienstag",
		name: "Warmwasser Timer Start 4 (Di)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "563",
		write: true,
	},
	WW_Dienstag_Ende4: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Dienstag",
		name: "Warmwasser Timer Ende 4 (Di)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "564",
		write: true,
	},
	WW_Dienstag_Start5: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Dienstag",
		name: "Warmwasser Timer Start 5 (Di)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "565",
		write: true,
	},
	WW_Dienstag_Ende5: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Dienstag",
		name: "Warmwasser Timer Ende 5 (Di)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "566",
		write: true,
	},

	// --- MITTWOCH (Basis 567) ---
	WW_Mittwoch_Start1: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Mittwoch",
		name: "Warmwasser Timer Start 1 (Mi)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "567",
		write: true,
	},
	WW_Mittwoch_Ende1: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Mittwoch",
		name: "Warmwasser Timer Ende 1 (Mi)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "568",
		write: true,
	},
	WW_Mittwoch_Start2: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Mittwoch",
		name: "Warmwasser Timer Start 2 (Mi)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "569",
		write: true,
	},
	WW_Mittwoch_Ende2: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Mittwoch",
		name: "Warmwasser Timer Ende 2 (Mi)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "570",
		write: true,
	},
	WW_Mittwoch_Start3: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Mittwoch",
		name: "Warmwasser Timer Start 3 (Mi)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "571",
		write: true,
	},
	WW_Mittwoch_Ende3: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Mittwoch",
		name: "Warmwasser Timer Ende 3 (Mi)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "572",
		write: true,
	},
	WW_Mittwoch_Start4: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Mittwoch",
		name: "Warmwasser Timer Start 4 (Mi)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "573",
		write: true,
	},
	WW_Mittwoch_Ende4: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Mittwoch",
		name: "Warmwasser Timer Ende 4 (Mi)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "574",
		write: true,
	},
	WW_Mittwoch_Start5: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Mittwoch",
		name: "Warmwasser Timer Start 5 (Mi)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "575",
		write: true,
	},
	WW_Mittwoch_Ende5: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Mittwoch",
		name: "Warmwasser Timer Ende 5 (Mi)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "576",
		write: true,
	},

	// --- DONNERSTAG (Basis 577) ---
	WW_Donnerstag_Start1: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Donnerstag",
		name: "Warmwasser Timer Start 1 (Do)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "577",
		write: true,
	},
	WW_Donnerstag_Ende1: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Donnerstag",
		name: "Warmwasser Timer Ende 1 (Do)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "578",
		write: true,
	},
	WW_Donnerstag_Start2: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Donnerstag",
		name: "Warmwasser Timer Start 2 (Do)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "579",
		write: true,
	},
	WW_Donnerstag_Ende2: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Donnerstag",
		name: "Warmwasser Timer Ende 2 (Do)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "580",
		write: true,
	},
	WW_Donnerstag_Start3: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Donnerstag",
		name: "Warmwasser Timer Start 3 (Do)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "581",
		write: true,
	},
	WW_Donnerstag_Ende3: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Donnerstag",
		name: "Warmwasser Timer Ende 3 (Do)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "582",
		write: true,
	},
	WW_Donnerstag_Start4: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Donnerstag",
		name: "Warmwasser Timer Start 4 (Do)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "583",
		write: true,
	},
	WW_Donnerstag_Ende4: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Donnerstag",
		name: "Warmwasser Timer Ende 4 (Do)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "584",
		write: true,
	},
	WW_Donnerstag_Start5: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Donnerstag",
		name: "Warmwasser Timer Start 5 (Do)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "585",
		write: true,
	},
	WW_Donnerstag_Ende5: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Donnerstag",
		name: "Warmwasser Timer Ende 5 (Do)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "586",
		write: true,
	},

	// --- FREITAG (Basis 587) ---
	WW_Freitag_Start1: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Freitag",
		name: "Warmwasser Timer Start 1 (Fr)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "587",
		write: true,
	},
	WW_Freitag_Ende1: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Freitag",
		name: "Warmwasser Timer Ende 1 (Fr)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "588",
		write: true,
	},
	WW_Freitag_Start2: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Freitag",
		name: "Warmwasser Timer Start 2 (Fr)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "589",
		write: true,
	},
	WW_Freitag_Ende2: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Freitag",
		name: "Warmwasser Timer Ende 2 (Fr)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "590",
		write: true,
	},
	WW_Freitag_Start3: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Freitag",
		name: "Warmwasser Timer Start 3 (Fr)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "591",
		write: true,
	},
	WW_Freitag_Ende3: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Freitag",
		name: "Warmwasser Timer Ende 3 (Fr)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "592",
		write: true,
	},
	WW_Freitag_Start4: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Freitag",
		name: "Warmwasser Timer Start 4 (Fr)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "593",
		write: true,
	},
	WW_Freitag_Ende4: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Freitag",
		name: "Warmwasser Timer Ende 4 (Fr)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "594",
		write: true,
	},
	WW_Freitag_Start5: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Freitag",
		name: "Warmwasser Timer Start 5 (Fr)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "595",
		write: true,
	},
	WW_Freitag_Ende5: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Freitag",
		name: "Warmwasser Timer Ende 5 (Fr)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "596",
		write: true,
	},

	// --- SAMSTAG (Basis 597) ---
	WW_Samstag_Start1: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Samstag",
		name: "Warmwasser Timer Start 1 (Sa)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "597",
		write: true,
	},
	WW_Samstag_Ende1: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Samstag",
		name: "Warmwasser Timer Ende 1 (Sa)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "598",
		write: true,
	},
	WW_Samstag_Start2: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Samstag",
		name: "Warmwasser Timer Start 2 (Sa)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "599",
		write: true,
	},
	WW_Samstag_Ende2: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Samstag",
		name: "Warmwasser Timer Ende 2 (Sa)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "600",
		write: true,
	},
	WW_Samstag_Start3: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Samstag",
		name: "Warmwasser Timer Start 3 (Sa)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "601",
		write: true,
	},
	WW_Samstag_Ende3: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Samstag",
		name: "Warmwasser Timer Ende 3 (Sa)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "602",
		write: true,
	},
	WW_Samstag_Start4: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Samstag",
		name: "Warmwasser Timer Start 4 (Sa)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "603",
		write: true,
	},
	WW_Samstag_Ende4: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Samstag",
		name: "Warmwasser Timer Ende 4 (Sa)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "604",
		write: true,
	},
	WW_Samstag_Start5: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Samstag",
		name: "Warmwasser Timer Start 5 (Sa)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "605",
		write: true,
	},
	WW_Samstag_Ende5: {
		folder: "Einstellungen.07_Tabellen.Warmwasser.Parameter.Days.Samstag",
		name: "Warmwasser Timer Ende 5 (Sa)",
		role: "value.datetime",
		type: "string",
		dataSource: "raw_parameter",
		luxWriteId: "606",
		write: true,
	},

	//Action
	Dump_Raw_To_Log: {
		folder: "Aktionen", // Oder ein anderer Ordner deiner Wahl, z.B. "Einstellungen.Adapter"
		name: "Raw Data in Log schreiben",
		role: "button",
		type: "boolean",
		isVirtual: true,
		write: true,
	},

	Regelung_Aktiv: {
		folder: "Aktionen",
		name: "Automatische Anlagenregelung ein-/ausschalten",
		role: "switch",
		type: "boolean",
		isVirtual: true,
		write: true,
		def: true,
	},

	Schreibe_Debug_Log: {
		folder: "Aktionen",
		name: "Erweiterte Logging-Ausgaben ein-/ausschalten",
		role: "switch",
		type: "boolean",
		isVirtual: true,
		write: true,
		def: false,
	},
};

// Runtime Injection für fehlende IDs
for (const key of Object.keys(STATE_MAPPING)) {
	if (!STATE_MAPPING[key].luxWriteId) {
		STATE_MAPPING[key].luxWriteId = key;
	}
}
